#!/usr/bin/python2

import os
import getpass
import commands
import sys
import fileinput
cmd=commands.getstatusoutput("hostname -i")
if cmd[0]==0:
	k=cmd[1]
while True:
	print "Welcome To Storage as a Service \n Choose the Storage type:-\n 1:Object NFS \n 2:Object SSHFS \n 3:block\n 4:Need More Space"
	x=raw_input('Enter Your Choice No')
	if x == '1':
		ce=commands.getstatusoutput("vgdisplay vg1|grep Free|cut -d' ' -f16")
		n=float(raw_input("Enter the required size in GB"))
		if n >= float(ce[1]):
			print "SORY WE DONT HAVE ENOUGH RESOURCE TRY AMAZON"
		else :
			uid=raw_input('Enter User Name')
			pas=getpass.getpass('Enter Password')
			os.system('useradd '  +uid)
			os.system("echo " +pas+ " | passwd " +pas+ " --stdin" )
			os.system("lvcreate --name "+uid+" --size "+str(n)+"G  vg1")
			os.system("mkfs.vfat /dev/vg1/"+uid)
			os.system("mkdir /staaso/"+uid)
			os.system("mount /dev/vg1/"+uid+" /staaso/"+uid)
			f1=open('/etc/exports','w+')
			f1.read()
			f1.write("/staaso/"+uid+ " *(rw,no_root_squash)")
			f1.close()
			os.system("/etc/init.d/nfs restart")
			f1=open('staasoclient','w+')
			f1.write("import os \nos.system('mkdir /media/rdbox')\nos.system('mount "+k+":/staaso/"+uid+" /media/rdbox')")
			f1.close()
			os.system('chmod +x staasoclient')			
			break
	elif x == '2':
		ce=commands.getstatusoutput("vgdisplay vg1|grep Free|cut -d' ' -f16")
		n=float(raw_input("Enter the required size in GB"))
		if n >= float(ce[1]):
			print "SORY WE DONT HAVE ENOUGH RESOURCE TRY AMAZON"
		else :
			uid=raw_input('Enter User Name')
			pas=getpass.getpass('Enter Password')
			os.system('useradd -s /usr/bin/firefox  '  +uid)
			os.system("echo " +pas+ " | passwd " +pas+ " --stdin" )
			os.system("lvcreate --name "+uid+" --size "+str(n)+"G  vg1")
			os.system("mkfs.vfat /dev/vg1/"+uid)
			os.system("mkdir /staaso/"+uid)
			os.system("mount /dev/vg1/"+uid+" /staaso/"+uid)
			os.system("chown "+uid+ " /staaso/"+uid)
			os.system("yum install sshfs -y")
			os.system("service sshd restart")
			f1=open('staasoclient','w+')
			f1.write("import os \nos.system('mkdir /media/rdbox')\nos.system('sshfs "+uid+"@"+k+":/staaso/"+uid+" /media/rdbox')")
			f1.close()
			os.system('chmod +x staasoclient')			
			break	
	elif x == '3':
		uid=raw_input('Enter User Name')
		pas=getpass.getpass('Enter Password')	
		os.system('useradd  '  +uid)
		os.system("echo " +pas+ " | passwd " +pas+ " --stdin" )
		os.system("lvcreate --name "+uid+" --size "+str(n)+"G  vg1")
		os.system("yum install scsi-target-utils")
		fi=open('/etc/tgt/target.conf','w+')		
		fi.read()
		fi.write("<target mystore"+uid+"> \n backing-store /dev/vg1/"+uid+"</target>")	
		fi.close()	
		os.system("setenforce 0;iptables -F;")
		os.system("yum install scsi-target-utils")
		os.system("mount /dev/vg1/"+uid+" /staaso/"+uid)
		os.system("service tgtd restart")
		fc=open('CLient'+uid,'w+')
		fc.write("")
		fc.close()			
		#fi.write("os.system('rm changet.desktop')")
		
		print "UNDER CONSTRUCTION"
		break
	elif x == "4" :
		uid=raw_input('Enter User Name')
		ce=commands.getstatusoutput("vgdisplay vg1|grep Free|cut -d' ' -f16")
		n=float(raw_input("Enter the required increased size in GB"))
		if n >= float(ce[1]):
			print "SORY WE DONT HAVE ENOUGH RESOURCE TRY AMAZON"
		else :
			os.system("lvextend --size "+str(n)+"G /dev/vg1/"+uid)
			os.system("resize2fs /dev/vg1/"+uid)
		break
	
	else :
		print "Kindly have a EYE TEST"
		break
